CREATE DATABASE rails_notification_test_production;
CREATE DATABASE rails_notification_test_production_cache;
CREATE DATABASE rails_notification_test_production_queue;
CREATE DATABASE rails_notification_test_production_cable;
